config/routes.rb
Rails.application.routes.draw do
  root 'signups#index'
  resources :signups
#   get '/signups', to: 'signups#index'
#   get '/signups/new', to: 'signups#new'
#   post '/signups', to: 'signups#create'
  # get '/signups/:id', to: 'signups#show', as: 'signup'
#   get '/signups/:id/edit', to: 'signups#edit', as: 'edit_signup'
#   patch '/signup/:id', to: 'signups#update'
#   put '/signup/:id', to: 'signups#update'
#   delete '/signup/:id', to: 'signups#delete'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]

  def index
    @signups = Signup.all
  end

  def new
    @signup = Signup.new
  end

  def show
  end

  def create
    @signup = Signup.new(signup_params)
    if @signup.save
      redirect_to signups_path
    else
      render :new
    end
  end

  def edit
    @signup = Signup.find(params[:id])
  end

  def update
    @signup = Signup.find(params[:id])
    if @signup.update(signup_params)
      redirect_to signups_path
    else
      render :edit
    end
  end

  def destroy
    @signup = Signup.find(params[:id])
    @signup.destroy
    redirect_to signups_path
  end

  private

    def set_signup
      @signup = Signup.find(params[:id])
    end
    def signup_params
      params.require(:signup).permit(:name, :surname, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud Ruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/24a7cebcbe.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
        <img src="https://lh3.googleusercontent.com/proxy/UqRLevFndmd-ipUAhCX4hXjictECpBwLJMUHZRkgj0atufXmgP69IAbvW2Z7GFAFzixft8fNPADjxG_riCt8iHNMwchhjRm_l-vEs2KYjIFNeEw05zM" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
          Crud Ruby on rails
      </a>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/signups/edit.html.erb
<div class="card mx-auto" style="width: 18rem;">
  <div class="card-body">
    <%= form_for @signup do |f| %>

    <div class="form-group">
      <%= f.label :Nombre%>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :Apellido%>
      <%= f.text_field :surname %>
    </div>
    <div class="form-group">
      <%= f.label :Edad%>
      <%= f.text_field :age %>
    </div>
    <div class="btn">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/signups/index.html.erb
<div class="container col-md-8">
  <h3 class="title">Listado de Regitros</h3>
  <table class="table">
    <thead class="thead-dark">
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">Edad</th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
    </thead>
<% @signups.each do |signup| %>
    <tbody>
        <td><%= signup.name %></td>
        <td><%= signup.surname %></td>
        <td><%= signup.age %></td>
        <td><%= link_to "Mostrar", signup%> &#128065;</td>
        <td><%= link_to "Editar", edit_signup_path(signup)%> 	&#128221;</td>
        <td><%= link_to "Eliminar", signup, method: :delete, data: {confirm: "Deseas eliminar eliminar este registro. "}%> &#10060;</td>
    </tbody>
    <% end %>
  </table>
  <%= link_to 'Nuevo registro', new_signup_path %>
</div>

app/views/signups/new.html.erb
<div class="card mx-auto" style="width: 18rem;">
  <div class="card-body">
    <%= form_for @signup do |f| %>

    <div class="form-group">
      <%= f.label :Nombre%>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :Apellido%>
      <%= f.text_field :surname %>
    </div>
    <div class="form-group">
      <%= f.label :Edad%>
      <%= f.text_field :age %>
    </div>
    <div class="btn">
      <%= f.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/signups/show.html.erb
<div class="container">
  <div class="card mb-4 mv" style="max-width: 360px;"">
    <div class="row no-gutters">
      <div class="col-md-4 p-1">
        <img src="https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png" class="card-img">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <div class="form-group">
            <strong>Nombre:</strong>
            <%= @signup.name %>
          </div>
          <div class="form-group">
            <strong>Apellido:</strong>
            <%= @signup.surname %>
          </div>
          <div class="form-group">
            <strong>Edad:</strong>
            <%= @signup.age %>
          </div>
            <%= link_to 'Editar', edit_signup_path(@signup) %>
            <%= link_to 'Atras', signups_path %>
        </div>
      </div>
    </div>
  </div>
</div>